README.git
sharness.sh
test/sharness.t

This is a straight-forward patch of a patch peff just posted to the git
mailing list:
(http://thread.gmane.org/gmane.comp.version-control.git/265874)
It adds a --chain-lint argument that will barf if you have a broken &&
chain in your test (and a test that tests whether it does).
You'll be pleased to know it detected no broken &&-chains in sharness :)

Add a linter that detects broken && chains

---

sharness.sh

In Git, "test-lib.sh" sources the GIT-BUILD-OPTIONS file
where SHELL_PATH is defined, and then exports SHELL_PATH,
so this environment variable is available to all the
test scripts.
In sharness there is no GIT-BUILD-OPTIONS, so "sharness.sh"
doesn't have SHELL_PATH defined, and doesn't export it.
This is bad because SHELL_PATH is used in "sharness.t".
Now "sharness.t" still works because the following works:
```
$ cat >test.sh <<EOF
echo "it works!"
EOF
$ chmod +x test.sh
$ ./test.sh
it works!
```
But it's still better in "sharness.sh" to define SHELL_PATH
if it is not already defined and to export it.

sharness.sh: export SHELL_PATH

---

README.md

go-ipfs is now hosted under https://github.com/ipfs/.

README.md: fix go-ipfs url

---

sharness.sh

Define `$test_results_path` in terms of `$this_test`, not `${SHARNESS_TEST_FILE%.$SHARNESS_TEST_EXTENSION}`.  The former is the basename of the latter, making it possible for `$0` to be an absolute path.

fix pathname of test-results/*.counts file

---

test/Makefile

Starting with v3.82, GNU make's wildcard function no longer sorts the
results.  Use the sort function to ensure that the test scripts are
run in the intended order (e.g., so that quick smoke tests are run
before more thorough tests).

sort *.t test scripts before running them

---

sharness.sh

If SHARNESS_TEST_DIRECTORY is not PWD, you cannot assume that you can create
and enter the trash directory without the full path.

Use full path to create/enter trash directory

---

.travis.yml
API.md
sharness.sh
test/sharness.t
test/test-terminal.perl

I'm not sure if this one will be acceptable, but we have a use case where our sharness test will reinvoke itself under our framework.
Becuase `TERM` is now sanitized, we unnecessarily lose color output from the secondary sharness.
This change simply uses `SHARNESS_SAVED_TERM` to save the original `TERM` value, then resets `TERM` if `SHARNESS_SAVED_TERM` is found.

save original TERM before sanitization

---

README.md
sharness.sh
test/sharness.t

The main contribution of this PR is to provide a summary of command-line options. I did this in response to https://github.com/git-multimail/git-multimail/issues/122#issuecomment-134552202 where a contributor didn't find --immediate.
While going through the list, I found --long-test which didn't work, so I also provide test&implementation for it.
Thanks for working on Sharness :-).

Clarify docs and implement --long-test

---

README.md
sharness.sh
test/sharness.t

In our project that uses sharness, we want to extend sharness with project-specific test functions, modify `PATH` and other environments, and do other per-test-file setup. However, to make it easier
to stay in sync with upstream sharness, we'd like to avoid modifying sharness.sh directly.
This PR is an attempt to address this need by optionally loading "test library extensions" from
`$SHARNESS_TEST_SRCDIR/sharness.d/*.sh` if the directory exists. We support multiple
extension files in case some sharness users in the future create reusable libraries these can be
shared as is amongst interested parties by simply dropping them into the `sharness.d` directory.
I would not consider this something to submit to upstream git, as their `test-lib.sh` is only meant for
a single project. However, …

support $SHARNESS_TEST_SRCDIR/sharness.d directory for per-project extensions

---

.travis.yml

This is a proposal to update the sharness travis-ci build to the new container based builder.
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/
Travis-CI container builds start much faster (almost instantaneously) and travis is slowly deprecating the older VM based builds.
Since the container builds start so quickly, there is no reason to force the `language: erlang` setting, so that was removed.
The only caveat is that `sudo` is not allowed in container builds. However, placing the installed prefix under `$HOME` seems to work around this, and hopefully testing from that location is sufficient.

travis-ci: update to container build infrastructure

---

README.md

The tests for azuki and git-spindle are the reason for my other patches, so
they provide some examples of the usage of the added functionality.

Add some more users of sharness to README.md

---

sharness.sh
test/sharness.t

It is better to have a `:` that ensures the script
ends with code 0, rather than rely on the previous
command.
This is an alternative to PR https://github.com/mlafeldt/sharness/pull/48

sharness: properly ensure it ends with code 0

---

README.md
sharness.sh
test/sharness.t

sharness redirects /dev/null to stdin for tests to make sure individual
tests accidently requiring input cannot hang the current test. However,
sometimes you just need to test an interactive program (for example,
when testing TOTP-based functionality). This patch lets you mark such
tests with the INTERACTIVE prereq and adds an --interactive-tests
argument to sharness.sh that will run those and will not redirect
/dev/null to the tests stdin when doing so.

Support interactive tests

---

CHANGELOG.md

This is to address issue #44.
If this is ok and merged, it should be tagged v1.0.0, and a GitHub release should be created using the new content in this PR.

CHANGELOG: add release notes for Sharness 1.0

---

README.md

This should fix links and update the "Authors" section following the maintainer change.

README.md: update following transfer to chriscool

---

test/sharness.t

The test 'empty sharness.d directory does not cause failure' fails on *BSD because it uses /bin/true.  *BSD places this executable in /usr/bin/true.
Replace /bin/true with true to use the shell builtin or find the executable via PATH.

Replace /bin/true with true

---

test/sharness.t

Change "suposedly" to "supposedly".

Fix spelling of "suposedly"

---

test/sharness.t

Test 23 (EXPENSIVE prereq not activated by default) fails when `sharness.t` is run with the `--long-tests` option.  When this option is specified, the TEST_LONG environment variable is set and passed on to the sub_test. This causes the EXPENSIVE prereq to be met, which causes sub_test 2 to not be skipped, which causes the overall test to fail:
```
$ ./sharness.t -l
ok 1 - sourcing sharness succeeds
ok 2 - success is reported like this
not ok 3 - pretend we have a known breakage # TODO known breakage
ok 4 - pretend we have a fully passing test suite
ok 5 - pretend we have a partially passing test suite
ok 6 - pretend we have a known breakage
ok 7 - pretend we have fixed a known breakage
ok 8 - pretend we have fixed one of two known breakages (run in sub sharness)
ok 9 - pretend we have a …
```

Fix long test of 'EXPENSIVE prereq not activated by default'

---

API.md
CONTRIBUTING.md
sharness.sh

Updates to tomdoc.sh (now at version 0.1.8) trigger a lot of changes in API.md.
Also, CONTRIBUTING.md now points to TomDoc's current home. (N.B., Even
the last version at its old home triggers a comparable number of API.md
changes.)

Fix four typos. Regenerate API.md with "make doc."

---

sharness.sh

In https://github.com/chriscool/sharness/issues/72 @sumpfralle suggests removing the shebang from `sharness.sh` as it is supposed to be sourced, not executed directly.
I think that indeed it could avoid mistakes and make it easier for packagers.

sharness: replace shebang with title

---

sharness.sh
test/sharness.t

This can be used used when a test is not stable or not finished for some reason.
When the test passed, an "ok" message is printed, but the number of
fixed tests is not incremented.
When it failed, a "not ok ... # TODO known breakage" message is
printed, and the number of tests still broken is incremented.

sharness: add test_expect_unstable()

---

sharness.sh

LF appears to not being used anymore so let's remove it.
Thanks @sumpfralle for finding that as part of https://github.com/chriscool/sharness/pull/82 !

sharness.sh: remove useless LF definition

---

sharness.sh

Looks like this was missed before releasing https://github.com/chriscool/sharness/releases/tag/v1.1.0. :wink:

Bump version

---

sharness.sh

The Git project has always used POSIX shell format for a reason.
The code should run in the least common denominator shell; not the
currently running shell.

Set proper default shell

---

lib-sharness/functions.sh
sharness.sh
test/sharness.t

I don't know why this was removed from Git's version.
It's incredibly useful to output everything to a temporary directory to
run the tests faster (if it's a memory mount).

test: sharness: add support for output directory

---

sharness.sh
test/sharness.t

This option can help a lot in debugging tests, as it shows
the last shell command that was executed.
It's especially useful along with -i and -v.

sharness: add option -x from Git's test-lib

---

test/test-terminal.perl

I work on a project that is converting from the "master-slave" terminology that a lot of projects are converting from.  Saw that it was used in our local copy of sharness.  I changed it to the following in our tree.  I thought I'd share it if you are interested in it as well.

test/test-terminal.perl: Rename master-slave terms

---

README.md

The manual install instructions haven't worked since since https://github.com/chriscool/sharness/pull/90. Let's update them.
This is an alternative to https://github.com/chriscool/sharness/pull/100.

README: update manual install instructions

---

.github/workflows/ci.yml

To minimize the opportunities for bugs and regressions, let's run
sharness test suite on every push and pull request.
Tests are ran on the latest versions of the operating systems currently
supported by github actions.

Run sharness test suite with github actions

---

test/sharness.t

In 3e0777c (test/sharness: normalize -x output before testing
it, 2019-06-27), we tried to normalize -x output before we
would test it, but it looks like this is sometimes not enough.
So let's also normalize the '+' characters that -x can output.
Fixes: https://github.com/chriscool/sharness/issues/104

test/sharness: normalize output more

---

.github/workflows/ci.yml
test/test-terminal.perl

This reverts commit 06aadc33d9b31b0bcdfd1cef121c7effa9781dde.
It seems that IO::Pty does not have a 'follower' method. The
method is named 'slave'. So we cannot really get rid of the
master-slave terminology until there is an upstream update
or until we find another Perl module to replace IO::Pty.
Fixes: https://github.com/chriscool/sharness/issues/105

Revert "test/test-terminal.perl: Rename master-slave terms"

---

vim/indent/sharness.vim

So that the sh indentation doesn't try to indent the lines after the
first command:
true &&
test x == x &&
echo success
Signed-off-by: Felipe Contreras <felipe.contreras@gmail.com>

vim: indent: remove continuation-line

---

lib-sharness/functions.sh

`test_seq()` uses double-quotes to protect the variable within its arithmetic expression; however, double-quotes inside such an expression are not treated specially.
Remove the double-quotes since they cause errors with some shells.  For example:
- Current versions of `dash`
```arithmetic expression: expecting primary: ""1" + 1"```
- OpenBSD 7.2 `sh`
```"1" + 1: unexpected `"'```
- Ubuntu 16.04 `bash-4.3.48`
```"1" + 1: syntax error: operand expected (error token is ""1" + 1")```
Also, remove the '$' character for variable expansion since tokens within an arithmetic expression undergo variable expansion, and this matches the coding style used in the rest of the file.

Fix test_seq arithmetic expression quoting

---

README.md

I (Christian Couder) am happy to pass on the maintainership of Sharness to Felipe. So I have transfered the repo from my `chriscool` GitHub account to his `felipec` GitHub account.
Thanks Felipe!

README: acknowledge maintainer change

---

sharness.sh

The zsh-specific parameter expansion ${(%):-%x} introduced in commit 96e0ea2c7 causes a parse error on NetBSD where /bin/sh cannot parse this syntax, even though it is inside a zsh-only conditional block.
The error occurs because the shell must parse the entire script before execution, and NetBSD's /bin/sh fails when it encounters the zsh-specific syntax with: "Syntax error: Bad substitution".
Wrap the assignment in eval to defer parsing until runtime, when the script is actually running under zsh.  This maintains the fix for the NO_FUNCTION_ARGZERO option while restoring compatibility with NetBSD's /bin/sh.
Tested on NetBSD 9.4 and 10.1 (without zsh installed) where the parsing error was reproducible and verified the eval wrapper resolves it.  Also tested on other platforms (most without …

Fix zsh parsing error on NetBSD
